web/router.ex
defmodule Twitchsap.Router do
  use Twitchsap.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Twitchsap do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/privacy", PageController, :privacy
    get "/play", PageController, :play
    get "/play/:id", PageController, :single_channel_play

    get    "/login",  SessionController, :new
    post   "/login",  SessionController, :create
    delete "/logout", SessionController, :delete

    resources "/registrations", RegistrationController, only: [:new, :create]
    resources "/events", EventController
    resources "/channels", ChannelController
    resources "/languages", LanguageController
    resources "/games", GameController
    resources "/streamtypes", StreamtypeController
    resources "/genders", GenderController
    resources "/platforms", PlatformController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Twitchsap do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Twitchsap.LayoutView do
  use Twitchsap.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Streamsap - Sap easily through streams</title>

    <link rel="apple-touch-icon" sizes="57x57" href="/icons/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/assets/icons/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/assets/icons/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/assets/icons/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/assets/icons/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/assets/icons/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/assets/icons/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/assets/icons/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/icons/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/assets/icons/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/icons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/assets/icons/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/icons/favicon-16x16.png">
    <link rel="manifest" href="/assets/icons/manifest.json">
    <link rel="icon" href="/assets/icons/favicon.ico" type="image/x-icon" />
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/assets/icons/ms-icon-144x144.png">

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/vendor.css") %>">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-73762823-2', 'auto');
      ga('send', 'pageview');

    </script>
  </head>

  <body>
    <nav class="navbar-inverse navbar navbar-default">
      <%= if logged_in?(@conn) do %>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon fa fa-bars"></span>
        </button>
      <% end %>
      <a class="navbar-brand" href="/">Streamsap</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <%= if logged_in?(@conn) do %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                More
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link "Channels", to: channel_path(@conn, :index), class: "nav-link dropdown-item" %>
                <%= link "Games", to: game_path(@conn, :index), class: "nav-link dropdown-item" %>
                <%= link "Genders", to: gender_path(@conn, :index), class: "nav-link dropdown-item" %>
                <%= link "Languages", to: language_path(@conn, :index), class: "nav-link dropdown-item" %>
                <%= link "Stream-types", to: streamtype_path(@conn, :index), class: "nav-link dropdown-item" %>
                <%= link "Platforms", to: platform_path(@conn, :index), class: "nav-link dropdown-item" %>
                <%= link "Add Admin", to: registration_path(@conn, :new), class: "nav-link dropdown-item" %>
                <%= link "Logout", to: session_path(@conn, :delete), method: :delete, class: "nav-link dropdown-item" %>
              </div>
            </li>
          <% else %>
            <!-- <li><%= link "Login",    to: "/login" %></li> -->
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container-fluid">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

      
    </div>

    <script src="<%= static_path(@conn, "/js/vendor.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>